name: Deploy PM2 Side Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Adjusted to a valid Node.js version

      - name: Stop previous PM2 process
        run: pm2 delete index.js || true
        continue-on-error: true

      - name: Install dependencies
        run: npm install

      - name: Start PM2 process
        run: |
          npm install pm2 -g

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/my-app/
          remote_host: ec2-3-138-36-150.us-east-2.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: '${{ secrets.SSH_PRIVATE_KEY }}'
      - name: Restart PM2
        run: |
          ssh -i '${{ secrets.SSH_PRIVATE_KEY }}' ubuntu@ec2-3-138-36-150.us-east-2.compute.amazonaws.com 'cd /var/www/my-app/ && pm2 restart index.js'
